services:
  # ----------------------------
  # Initialize Kafka
  # ----------------------------
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: kafka_broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - ./data:/tmp/data

  # ----------------------------
  # Initialize Kafka configuration
  # ----------------------------
  init-kafka:
    image: apache/kafka:latest
    depends_on:
      - broker
    entrypoint: ['/bin/bash', '-c']
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka_broker:29092 --list
      
      echo -e 'Creating kafka topics'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka_broker:29092 --create --if-not-exists --topic station-info --replication-factor 1 --partitions 1
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka_broker:29092 --create --if-not-exists --topic station-status --replication-factor 1 --partitions 1
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka_broker:29092 --create --if-not-exists --topic station-status-enriched --replication-factor 1 --partitions 1
      
      echo -e 'Successfully created the following topics:'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka_broker:29092 --list
      "
      

  # ----------------------------
  # Initialize Flink JobManager
  # ----------------------------
  jobmanager:
    image: flink:1.20.0-scala_2.12-java11
    container_name: flink_jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081"   # Flink Web UI
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    depends_on:
      - broker
    volumes:
      - ./data:/opt/flink/data   # mount local ./data into Flink

  # ----------------------------
  # Initialize Flink TaskManager
  # ----------------------------
  taskmanager:
    image: flink:1.20.0-scala_2.12-java11
    container_name: flink_taskmanager
    hostname: taskmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    depends_on:
      - jobmanager
    volumes:
      - ./data:/opt/flink/data   # mount local ./data into Flink