#FROM flink:1.20.0-scala_2.12-java11
#
## Install Python
#RUN apt-get update -y && \
#apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev libffi-dev liblzma-dev && \
#wget https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz && \
#tar -xvf Python-3.10.0.tgz && \
#cd Python-3.10.0 && \
#./configure --without-tests --enable-shared && \
#make -j6 && \
#make install && \
#ldconfig /usr/local/lib && \
#cd .. && rm -f Python-3.10.0.tgz && rm -rf Python-3.10.0 && \
#ln -s /usr/local/bin/python3 /usr/local/bin/python && \
#apt-get clean && \
#rm -rf /var/lib/apt/lists/*
#
## Ensure python command points to python3
#RUN ln -s /usr/bin/python3 /usr/bin/python
#
## install PyFlink
#COPY requirements-flink.txt .
#RUN python -m pip install --upgrade pip; \
#    pip3 install -r requirements-flink.txt  --no-cache-dir;
#
#
## Download connector libraries
#RUN wget -P /opt/flink/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-python/1.20.0/flink-python-1.20.0.jar; \
#    wget -P /opt/flink/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/1.16.2/flink-sql-connector-kafka-1.16.2.jar; \
##    wget -P /opt/flink/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.4.0-1.20/flink-sql-connector-kafka-3.4.0-1.20.jar; \
##    wget -P /opt/flink/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/4.0.1-2.0/flink-sql-connector-kafka-4.0.1-2.0.jar;

